### ISSUE TITLE
Blank PNG when using downloadPng() function

### ISSUE THREAD

**Issue by Cool-Katt** [cy6erskunk/svg-crowbar#407]
Hi, 

First, thank you for your work. 
I'm trying to export an Svg rendered by react-d3-tree (https://github.com/bkrem/react-d3-tree). When exporting to SVG file directly using downloadSvg() it functions as expected. However when trying to export to PNG file, it results in a blank white PNG.
The SVG element uses internal styling and is directly drawn in a parent div, not in a canvas.

Also noticed that when exporting to SVG file, the dimensions are those of the parent div, which I think is expected, but calling getBBox() on the svg element itself returns the dimensions as zeros

**Comment by cy6erskunk** [comment]
Hello @Cool-Katt and thanks for creating the issue! 
A couple of questions from my side to clarify it:
- Do you have the issue with all the Svg rendered by react-d3-tree or with a particular one?
- Which browser are you using?
- Would you have an example somewhere (e.g. codesandbox, or a code snippet)?

**Comment by Cool-Katt** [comment]
Hi there @cy6erskunk,

To try and answer your questions:

- I'm only using react-d3-tree once in my app but as far as I've tested the issue affects any tree drawn, regardless of data
- Chrome Version 91.0.4472.114 (Official Build) (64-bit)
- https://codesandbox.io/s/svg-crowbar-png-export-issue-5sxpc?file=/src/PITree.js (as accurate to the real application as i could get)

Thanks for the reply!

**Comment by cy6erskunk** [comment]
Hey @Cool-Katt , thanks for the answers!
I believe the issue here is that `getBoundingClientRect` does not work when it's used with a cloned DOM element. Using on the original element mounted to DOM works pretty well: 
```js
downloadPng(document.querySelector('.rd3t-svg'), 'PITree', {css: 'internal'});
```
It still creates too wide PNG file, because container has `100%` width as a block elemnt - just having an `inline-block` element solves the issue.

**Comment by Cool-Katt** [comment]
Thank you!
This did resolve the issue. I assume it has to do with the cloned element not having any actual size because it's not attached to the DOM?
